dist: trusty
sudo: false

language: java
jdk:
  - oraclejdk8

install: true

script: .travis/script.sh

deploy:
  - provider: script
    skip_cleanup: true
    script: .travis/deploy_jenkins_plugin.sh
    on:
      jdk: oraclejdk8
      repo: jenkinsci/doktor-plugin
      tags: true
  - provider: releases
    api_key:
      secure: OI6seANBD//8s731SIUzAVIo32qvg80M/oS/gI6kAhxuRJnbMv4Z38Dk8Dx84qjARZOUqvst/Bzon+2pbO4lEDx6Fo+oVvCsX6nCitpr+21vvosruHbFNX0AaIisJi2rHJLu9bPcXtFH0A1e8OXWOYqG2v4J30LVohza6JafcgUM2q7l3IMb00tABc04FVjsBHrmPAPKyqghHadB9z3T3yVfYZL9BhQBc6kUFUYStRaRGWr8hIL34pKlTlnjqh6hzN4tCwHnYzXKH1j/hTCke4lY++g4nmIkYsrGXK9asP7RngScf1cqy0VRY260BFA9iim1D32t+246eByYNAAzGkw2Pl2RtHfEWWQNwb2tS2SNbbpE5CM/nmi+tnaGhD2DRrfoVZqPuZtfBfWixY39liCfBMLPngEcKvwNtZW+FLZgt0jqdSDnBXQvIMkyMYTq8vBT6Qyevy0tGli0lDhNT8I3Suv+6j2ffxzyIU8Ou9FiFWqeDPs0D0pT5lo7mhKcusL+aBKr47lxhH89ZrHE4wbR1xaEe57RK2qfPZdR3hjXtBHbFo+OHCubqGzbwP6qwmlNUxenI6U10yyRpuO/Pb9wtQJJWYVfzrv3oS0HrrSdOsfedhiZrfqbT1N7Xhd3ynMzisf3LHjRppUOXLY9LI62UfdqHjWPHBTIGRGF0BY=
    file: build/libs/doktor.jpi
    skip_cleanup: true
    on:
      jdk: oraclejdk8
      repo: jenkinsci/doktor-plugin
      tags: true
