#!/usr/bin/env ansible-playbook

---
- name: Configure Confluence
  hosts: confluence
  vars:
    pip_install_packages:
      - name: docker
  roles:
    - role: geerlingguy.docker
      become: true
      become_user: root
    - role: geerlingguy.pip
      become: true
      become_user: root
    - role: confluence
      become: true
      become_user: root
